spring:
  servlet:
    multipart:
      max-file-size: -1
  datasource:
    url: jdbc:mysql://localhost:3306/driver?serverTimezone=UTC
    username: root
    password: coderslab
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
media:
  address: localhost
  port: 8081

