spring:
  datasource:
    url: jdbc:mysql://localhost:3306/driver?serverTimezone=UTC
    username: root
    password: coderslab
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
